### ISSUE TITLE
main resources buildings

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-user-stories#10]
## Value Proposition

**Als** user
**brauche ich** die Haupt Ressourcen Produktion Gebäude
**um** eine Produktion jeglicher Ressourcen bereitzustellen

## Description

![image](https://user-images.githubusercontent.com/77203530/179916050-f60b410b-82fe-411c-b5e6-855cb635e588.png)

## Acceptance Criteria

- [ ] Standardproduktion Geld + Gebäude Produktion Geld =  20 + 30 = 50/h
- [ ] Standardproduktion Eisen + Gebäude Produktion Eisen =  10 + 20 = 40/h
- [ ] Standardproduktion Treibstoff + Gebäude Produktion Treibstoff  =  0 + 10 = 10/h

## Tasks

(for developers team)

- [ ] Erstellen von Statischen Gebäude Daten (Gebäudename, Ertrag, Verbrauch, Bau Dauer )

**Comment by PReichetanz** [comment]
Hi Thomas,

I still like this user story very much! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Description
- I reconsidered the wireframe again: I think it's better to write down the correct building names instead of "Building Name" on each card. This way, it becomes clear which card is for solar energy, money, etc.
- It would be ideal if you could change this already here, but I think it's fine if you start with the correct names in your next user story.

## Acceptance Criteria
- There are some features not yet touched. You could add something like 
  - "Bei jedem weiterem Upgrade erhöht sich die Gebäudeproduktion exponentiell / um einen bestimmten Faktor."
  - "Wenn es nicht genügend Geld / Eisen gibt, kann ein Gebäude nicht gebaut / geupdated werden."
  - "Die Ressourcen Eisen, Geld und Treibstoff können nicht negativ sein."
  - "Wenn ein Gebäude gebaut wird, dass mehr Energie verbraucht, als verfügbar ist, zeigt die Energieanzeige die entsprechende negative Zahl an."

**Comment by tomsmulski** [comment]
thanks for the feedback, i have changed the content
