### ISSUE TITLE
building navigation

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-user-stories#11]
## Value Proposition

**Als** user
**brauche ich** eine bessere Übersicht der Gebäude
**um** die Gebäude Übersicht Dynamisch darzustellen

## Description

![image](https://user-images.githubusercontent.com/77203530/179923163-6d8ae9dd-8453-485a-8151-9e74bff4ddc5.png)

## Acceptance Criteria

- [ ] Gebäude in eine Scrollbare Navigation
- [ ] Gebäudename
- [ ] Aktuelle Gebäudestufe
- [ ] Aktuell ausgewähltes Gebäude hervorherben
- [ ] Nicht bau bare Gebäude markiert

## Tasks

(for developers team)

- [ ] Erstelle components/buildingNavigation

**Comment by chris-yooo** [comment]
Ich habe mir von der ersten User Story bis jetzt alle angeschaut und verstanden was du vorhast.
Das aus user sotry 3 hier die ganzen gebäude dann auftauchen ist mir ebenfalls klar.

Ich würde glatt behaupten das du für den ersten sprint den wir machen genug backlog's hast :)

weiter so !
