### ISSUE TITLE
technology manual

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-user-stories#12]
## Value Proposition

**Als** User
**brauche ich** eine erweiterte Beschreibung des Gebäudes
**um** eventuelle Voraussetzung, Gebäude stufen Produktionsfaktor zu begutachten

## Description

![image](https://user-images.githubusercontent.com/77203530/179983640-73d8c3f4-4bdd-4dd5-9622-bf9a6f1b7c7a.png)

## Acceptance Criteria

- [ ] Ein Button für das Handbuch
- [ ] Eine Detaillierte Beschreibung des Gebäudes (Text, Stufe, Produktionswert, Differenz)

## Tasks

(for developers team)

- [ ] Overlay der Beschreibung
- [ ] Erstelle components/manual
