### ISSUE TITLE
Overview Citycard

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-user-stories#6]
## Value Proposition

**As a user** 
**I need** I see a city image and the city name
**to be able to** to see the city name and image

## Description

![image](https://user-images.githubusercontent.com/77203530/179690548-7d4d7e30-b4ff-4747-b856-f7c8b6cc565f.png)

## Acceptance Criteria

- [ ] show the city name
- [ ] show the city image

## Tasks

(for developers team)

- [ ] build a card element to display the city name and image
